### ISSUE TITLE
Tomar notas

### ISSUE THREAD

**Issue by adpadillar** [Gorchon/BrainyPad#26]
## Historia de usuario

Como Luis, desarrollador en una empresa de software, quiero tomar notas sobre mis standup meetings dentro de brainy pad, para poder buscarlas y hacer referencia a ellas si se me olvida algo

## Tareas

- [x] Creación de notas
- [x] Edición de notas
- [x] Guardado de notas en DB
- [x] Búsqueda de notas

**Comment by Y0z64** [comment]
#35
