### ISSUE TITLE
Evitar notas falsas 

### ISSUE THREAD

**Issue by HEmilGS** [Gorchon/BrainyPad#37]
mira vro, resulta que cuando le das crear nota y dices "mejor no vro" y le das en cancelar, de todas formas se crea una nota sin titulo. Arreglalo vro
<img width="966" alt="Captura de pantalla 2024-06-11 a la(s) 7 22 27 p m" src="https://github.com/Gorchon/BrainyPad/assets/113577734/6af466c2-1e0e-442e-aa59-d380566e07c8">

**Comment by adpadillar** [comment]
No tan relacionado pero si funciona ya el botón de borrar notas?

**Comment by HEmilGS** [comment]
> No tan relacionado pero si funciona ya el botón de borrar notas?

nop, solo en archivos
